/* Auth Actions Types */
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const WRONG_USER_PASS = 'WRONG_USER_PASS';
export const FROM_URL = 'FROM_URL';

/* App Actions Types */
export const LOADING = 'LOADING';
export const REVEAL = 'REVEAL';
export const REVEAL_LOGO = 'REVEAL_LOGO';
export const SHRINK_LOGO = 'SHRINK_LOGO';
export const SHOW_MY_MODAL = 'SHOW_MY_MODAL';
export const SUBMIT_TYPE = 'SUBMIT_TYPE';

/* User Actions Types */
export const SHOW_CHECK_IN_OUT = 'SHOW_CHECK_IN_OUT';
export const SEARCH_BY_MOBILE = 'SEARCH_BY_MOBILE';
export const SHEET_DATE = 'SHEET_DATE';
export const NEW_SHEET_ID = 'NEW_SHEET_ID';
export const NUMBER_EXISTS = 'NUMBER_EXISTS';
export const VALUES_MATCHED = 'VALUES_MATCHED';
export const INVITE_NUMBER_EXISTS = 'INVITE_NUMBER_EXISTS';
export const INVITE_VALUES_MATCHED = 'INVITE_VALUES_MATCHED';
export const HOURS_DAILY_RATES = 'HOURS_DAILY_RATES';
export const ACTIVE_USERS_LIST = 'ACTIVE_USERS_LIST';
export const NON_ACTIVE_USERS_LIST = 'NON_ACTIVE_USERS_LIST';

export const ON_SEARCH_SUBMIT = 'ON_SEARCH_SUBMIT';
export const ON_NEW_USER_SUBMIT = 'ON_NEW_USER_SUBMIT';
export const ON_CHECK_IN_OUT_SUBMIT = 'ON_CHECK_IN_OUT_SUBMIT';
export const ON_CONFIRM_DELETE_CHECK_IN_SUBMIT =
  'ON_CONFIRM_DELETE_CHECK_IN_SUBMIT';
export const ON_CONFIRM_DELETE_CHECK_OUT_SUBMIT =
  'ON_CONFIRM_DELETE_CHECK_OUT_SUBMIT';
export const ON_DELETE_CHECK_IN_SUBMIT = 'ON_DELETE_CHECK_IN_SUBMIT';
export const ON_DELETE_CHECK_OUT_SUBMIT = 'ON_DELETE_CHECK_OUT_SUBMIT';
export const ON_UPDATE_CHECK_IN_SUBMIT = 'ON_UPDATE_CHECK_IN_SUBMIT';
export const ON_UPDATE_CHECK_OUT_SUBMIT = 'ON_UPDATE_CHECK_OUT_SUBMIT';

export const CHECK_IN_OUT_STATUS = 'CHECK_IN_OUT_STATUS';
export const CHECKED_IN_STATUS = 'CHECKED_IN_STATUS';
export const CHECKED_OUT_STATUS = 'CHECKED_OUT_STATUS';

export const CLEAR_PREV_USER_STATE = 'CLEAR_PREV_USER_STATE';
export const CLEAR_PREV_INVITE_USER_STATE = 'CLEAR_PREV_INVITE_USER_STATE';

export const CALC_DURATION_COST = 'CALC_DURATION_COST';
export const CALC_REMAINING_HOURS = 'CALC_REMAINING_HOURS';
export const CALC_REMAINING_OF_TEN_DAYS = 'CALC_REMAINING_OF_TEN_DAYS';

export const ERROR = 'ERROR';
